#!/usr/bin/env bash
# Install and uninstall the Chrome NativeMessaging host whitelist file for the
# Keybase extension.
#
# Usage:
#   ./install_host
#   ./install_host uninstall
#
# It can be run multiple times. The whitelist will be overwritten each time.

realpath() {
  if [[ $1 = /* ]]; then
    echo "$1"
  else
    echo "$PWD/${1#./}"
  fi
}

detect() {
  local chrome_file="io.keybase.kbnm.json"
  local firefox_file="keybase.json"

  # Find where the NativeMessagingHosts whitelist lives for this platform.
  whoami="$(whoami)"
  if [[ "$(uname -s)" == "Darwin" ]]; then
    # Mac
    if [[ "$whoami" == "root" ]]; then
      echo "/Library/Google/Chrome/NativeMessagingHosts/${chrome_file}"
      echo "/Library/Application Support/Mozilla/NativeMessagingHosts/${firefox_file}"
    else
      echo "$HOME/Library/Application Support/Google/Chrome/NativeMessagingHosts/${chrome_file}"
      echo "$HOME/Library/Application Support/Mozilla/NativeMessagingHosts/${firefox_file}"
    fi
  else
    # Linux
    if [[ "$whoami" == "root" ]]; then
      echo "/etc/opt/chrome/native-messaging-hosts/${chrome_file}"
      echo "/usr/lib/mozilla/native-messaging-hosts/${firefox_file}"
    else
      echo "$HOME/.config/google-chrome/NativeMessagingHosts/${chrome_file}"
      echo "$HOME/.mozilla/native-messaging-hosts/${firefox_file}"
    fi
  fi
}

install() {
  # Install the whitelist.
  declare target="$1"

  local target_dir="$(dirname "$target")"
  if [[ ! -d "$target_dir" ]]; then
    mkdir -p "$target_dir"
  fi

  local here="$(dirname $(realpath "$BASH_SOURCE"))"
  local host_path="$(which "kbnm" || echo "$here/kbnm")"

  if [[ ! -x "$host_path" ]]; then
    # Is it in GOPATH, but not PATH?
    host_path="$GOPATH/bin/kbnm"
  fi

  if [[ ! -x "$host_path" ]]; then
    echo "failed to find kbnm executable, make sure it's in your \$PATH."
    exit 2
  fi

  echo "Writing: $target"
  cat "$here/host_json.template" \
    | sed "s|@@HOST_PATH@@|$host_path|g" \
    > "$target"

  chmod +r "$target"

  cat "$target"

  echo "Success."
}

uninstall() {
  # Uninstall the whitelist.
  declare target="$1"

  rm "$target" && echo "Removed NativeMessaging whitelist: $target" || echo "Install not found: $target"
}


main() {
  set -eou pipefail; [[ "${TRACE:-}" ]] && set -x

  declare cmd="${1:-}"

  detect | while read target; do
    if [[ "$cmd" == "uninstall" ]]; then
      uninstall "$target"
    else
      install "$target"
    fi
  done
}


[[ "$0" == "$BASH_SOURCE" ]] && main "$@"
